services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_DATABASE=modulecdb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - sudsyNetwork

  api:
    build: ./backend/api/
    container_name: api
    env_file:
      - ./backend/api/.env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sudsyNetwork

  m001:
    build: ./backend/washingMachine
    environment:
      MACHINE_ID: M001
      MACHINE_NAME: Sudsy WM-0001 
      MACHINE_TYPE: Washing machine
      MACHINE_BRAND: Samsung
      MACHINE_MODEL: WF10000
    container_name: M001 
    networks:
      - sudsyNetwork

  m002:
    build: ./backend/washingMachine
    environment:
      MACHINE_ID: M002
      MACHINE_NAME: Sudsy WM-0002
      MACHINE_TYPE: Washing machine
      MACHINE_BRAND: Samsung
      MACHINE_MODEL: WF10000
    container_name: M002
    networks:
      - sudsyNetwork

  m003:
    build: ./backend/washingMachine
    environment:
      MACHINE_ID: M003
      MACHINE_NAME: Sudsy WM-0003
      MACHINE_TYPE: Washing machine
      MACHINE_BRAND: Samsung
      MACHINE_MODEL: WF10000
    container_name: M003 
    networks:
      - sudsyNetwork

  m004:
    build: ./backend/washingMachine
    environment:
      MACHINE_ID: M004
      MACHINE_NAME: Sudsy WM-0004
      MACHINE_TYPE: Washing machine
      MACHINE_BRAND: Samsung
      MACHINE_MODEL: WF10000
    container_name: M004 
    networks:
      - sudsyNetwork

networks:
  sudsyNetwork:
    driver: bridge

volumes:
  db_data:
